# for logging into the Ops Manager UI
apiVersion: v1
data:
  FirstName: VmluY2VudA==
  LastName: TGl1
  # vemjuh-kezhip-8buhqY
  Password: dmVtanVoLWtlemhpcC04YnVocVkK
  Username: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: "2023-08-03T19:19:57Z"
  name: om-admin-secret
  namespace: mongodb
  resourceVersion: "6890001"
  uid: c8a422b3-d5a2-4c9b-9428-44caf765e4d5
type: Opaque
