apiVersion: v1
kind: Pod
metadata:
  name: mnesia-sh
  namespace: hypermnesia
spec:
  containers:
  - image: cuso4/hypermnesia
    command:
      - sleep
      - "36000"
    imagePullPolicy: IfNotPresent
    name: mnesia-sh
  restartPolicy: Always