apiVersion: v1
kind: Secret
metadata:
  name: mypostgres-secret
  namespace: postgresql
type: Opaque
stringData:
  superUserPassword: postgresSuperUserPsw
  replicationUserPassword: postgresReplicaPsw
                    