apiVersion: v1
kind: Pod
metadata:
  name: "postgres-sh"
  namespace: postgresql
  labels:
    app: "postgres-sh"
spec:
  containers:
  - name: postgres-sh
    image: cuso4/postgres:latest
    command:
      - sleep
      - "36000"
    imagePullPolicy: Always
  restartPolicy: Always